name: money
version: '1.0-SNAPSHOT'
main: org.testmode.asd.Asd
api-version: '1.21'

commands:
  테스트:
    description: "테스트"
    permission: 'op'
    usage: "사용법: 테스트 인데 뭘 사용법을 물어보노"
  돈:
    description: "돈"
    usage: "명령어가 잘못되었습니다."
  sys_money:
    description: "시스템에서 플레이어에게 돈을 지급합니다"
    usage: "/sys_money <int_value>"
    permission: 'op'
  상점:
    description: "/상점 도움말 입력시 상점 명령어에 관한 정보를 얻을수 있습니다"
    usage: "/상점"
